version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.2.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 127.0.0.0.1:9090:9090

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/sample.yaml:/usr/share/grafana/conf/provisioning/dashboards/sample.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/datasources/datasource.yaml:/usr/share/grafana/conf/provisioning/datasources/sample.yaml
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

  coinmarketcap-exporter:
     ports:
      - 9101:9101
     build:
          context: ./
          dockerfile: Dockerfile
     image: patsancu/coinmarketcap-exporter:latest
