{
 "title": "Crypto Currency Tracker",
 "description": "This is a dashboard that uses Docker, Prometheus, Grafana and the coinmarketcap-exporter and displays cryptocurrency trends for Bitcoin, Ethereum, Litecoin, and a ton more currencies.\r\n",
 "tags": [
  "crypto",
  "dashboard"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "name", "label": "name", "query": "label_values(name)" }
  ]
 },
 "panels": [
  {
   "title": "Cardano - Percent Change in USD",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_usd{name=~\"Cardano\"} - coin_market_price_usd{name=~\"Cardano\"} offset 24h) / coin_market_price_usd{name=~\"Cardano\"}"
    }
   ]
  },
  {
   "title": "Bitcoin - Percent Change in USD",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_usd{name=~\"Bitcoin\"} - coin_market_price_usd{name=~\"Bitcoin\"} offset 24h) / coin_market_price_usd{name=~\"Bitcoin\"}"
    }
   ]
  },
  {
   "title": "RChain - Percent Change",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_usd{name=~\"RChain\"} - coin_market_price_usd{name=~\"RChain\"} offset 24h) / coin_market_price_usd{name=~\"RChain\"}"
    }
   ]
  },
  {
   "title": "Ripple - Percent Change",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(coin_market_price_usd{name=~\"Ripple\"} - coin_market_price_usd{name=~\"Ripple\"} offset 24h) / coin_market_price_usd{name=~\"Ripple\"}"
    }
   ]
  },
  {
   "title": "$name Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"Cardano\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Stellar Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"Stellar\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Bitcoin Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"RChain\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Dash Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"Dash\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Ripple Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"Ripple\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Rchain Price in USD",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"RChain\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Totals in euros",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"Cardano\"}*$cardano_units*$usd_to_eur",
     "legendFormat": "Cardano"
    },
    {
     "expr": "coin_market_price_usd{name=~\"Bitcoin\"}*$bitcoin_units*$usd_to_eur",
     "legendFormat": "Bitcoin"
    },
    {
     "expr": "coin_market_price_usd{name=~\"Stellar\"}*$lumens_units*$usd_to_eur",
     "legendFormat": "Stellar"
    },
    {
     "expr": "coin_market_price_usd{name=~\"RChain\"}*$rchain_units*$usd_to_eur",
     "legendFormat": "Rchain"
    },
    {
     "expr": "coin_market_price_usd{name=~\"Dash\"}*$dash_units*$usd_to_eur",
     "legendFormat": "Dash"
    }
   ]
  },
  {
   "title": "$name - Volume",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_24h_volume_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "$name Difference in BTC price from 24 hours ago",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_btc{name=~\"$name\"} - coin_market_price_btc{name=~\"$name\"} offset 24h",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "$name - USD",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 25 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Rchain",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 27 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"RChain\"}*$rchain_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "Bitcoin",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 27 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"Bitcoin\"}*$bitcoin_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "Stellar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 27 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"Stellar\"}*$lumens_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "Cardano",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 27 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"Cardano\"}*$cardano_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "Dash",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 27 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"Dash\"}*$dash_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "Ripple",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 27 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "expr": "coin_market_price_usd{name=\"Ripple\"}*$ripple_units*$usd_to_eur"
    }
   ]
  },
  {
   "title": "$name - Market Cap",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 30 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "expr": "coin_market_market_cap_usd{name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Top 5 biggest % Change in 24 Hours",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, coin_market_percent_change_24h) by (value)",
     "legendFormat": "{{symbol}}"
    }
   ]
  },
  {
   "title": "$name Pice Heat Map",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"$name\"}"
    }
   ]
  },
  {
   "title": "$name Price Difference in USD from 24 hours ago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "coin_market_price_usd{name=~\"$name\"} - coin_market_price_usd{name=~\"$name\"} offset 24h",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Top 5 Market Caps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, coin_market_market_cap_usd)by (value)",
     "legendFormat": "{{symbol}}"
    }
   ]
  }
 ]
}